name = "ElectroStimulatorControllers"
uuid = "8a395c1f-5bee-4f3c-8ce9-3dbd60ecfd91"
authors = ["michikawa07 <michikawa.ryohei@gmail.com>"]
version = "0.1.0"

[deps]
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SerialPorts = "5d0f9de7-4c7f-54f5-bec2-484e8c04014e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
